# Generated by Django 5.1.1 on 2024-10-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='password',
        ),
        migrations.AddField(
            model_name='credential',
            name='encrypted_password',
            field=models.TextField(default='dummy_password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credential',
            name='module',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='credential',
            name='system',
            field=models.CharField(max_length=100),
        ),
    ]
