# Generated by Django 5.1.1 on 2024-10-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema', '0002_remove_credential_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='login',
            field=models.CharField(default='default_login', max_length=100),
        ),
    ]
